import { Metadata } from 'next';

import { WrapperAuth } from '@/features/auth';

export const metadata: Metadata = {
	title: 'MOSMAP | Геоаналитика',
	description: 'Generated by create next app',
	icons: {
		icon: '/images/icons/logo_mini.svg',
	},
};

export default function AuthPage() {
	return <WrapperAuth />;
}
