import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import { cookies } from 'next/headers';

import './globals.css';
import MainProvider from './providers/MainProvider';
import { TOKEN_COOKIE_NAME } from '@/shared/constants';
import Footer from '@/widgets/footer/ui/Footer';
import Header from '@/widgets/header/ui/Header';

const inter = Inter({
	weight: ['400', '500', '600'],
	subsets: ['cyrillic'],
	variable: '--font-inter',
	display: 'swap',
});

const intro = localFont({
	src: '../../public/fonts/Intro.otf',
	variable: '--font-intro',
	weight: '900',
});

export const metadata: Metadata = {
	title: 'MOSMAP | Геоаналитика',
	description: 'Generated by create next app',
	icons: {
		icon: '/images/icons/logo_mini.svg',
	},
};

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	maximumScale: 1,
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const token = (await cookies()).get(TOKEN_COOKIE_NAME)?.value;

	return (
		<html lang='ru' className={`${inter.variable} ${intro.variable}`}>
			<body className={`${inter.className} antialiased `}>
				<MainProvider token={token}>
					<div className='flex flex-col h-screen'>
						<Header />
						<main className='flex-1 flex min-h-0'>{children}</main>
						<Footer />
					</div>
				</MainProvider>
			</body>
		</html>
	);
}
